# Generated by Django 5.0.7 on 2024-08-07 06:00

from django.db import migrations

#two statements are being suppied 
#1 for upgrading and 2 for downgrading datbase
# """" are used for giving multile lines as variables in python
# INSERT INTO store_collection (title) VALUES ('collection1') -->> for upgrading which means its for inserting the values 
# DELETE FROM store_collection WHERE title='collection1' -->> for downgrading or undoing the values inserted

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RunSQL("""
                            INSERT INTO store_collection (title)
                            VALUES ('collection1')
                            ""","""
                            DELETE FROM store_collection
                            WHERE title='collection1'
                            """)
    ]
